/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Mai El Shahed
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *===
 ******************************************************************************
 */

#include <stdint.h>

#include "RCC_interface.h"
#include "SysTick_interface.h"
#include "NVIC_interface.h"
#include "GPIO_interface.h"

volatile uint8_t usart3_interrupt_flag = 0;


int main(void)
{

    RCC_SETCLK(HSI,RCC_ON);
    RCC_SETSYSCLK(SW_HSI);  //  Switch system clock to PLL
    SystemCoreClockUpdate();   // Update core clock variable
 	SysTick_Init(ProcessorAHB); // Initialize SysTick with new frequency


 	SysTick_Init(ProcessorAHB); // Initialize SysTick with new frequency

 	 	    RCC_AHB1_enable(GPIOAEN);   // Enable GPIOA
 	 	   RCC_AHB1_enable(GPIOCEN);   // Enable GPIOC clock
pin_configer_t PINA5_LED={
		.port=PORTA,
		.pinNum=5,
		.mode=OUTPUT,
		.speed=LOW,
		.outputtype=PUSH_PULL,
		.pulltype=NOPULL
};

GPIO_u8pininit(&PINA5_LED);

ENABLE_interrupt(USART3);
SET_PendingFlag(USART3);


while(1)
{

    usart3_interrupt_flag = 0;    // flag

            GPIO_u8setpinvalue(PORTA, PIN5, PIN_HIGH); // on led
            Delay_ms(500);

            GPIO_u8setpinvalue(PORTA, PIN5, PIN_LOW); // off led
            Delay_ms(500);

            GPIO_u8setpinvalue(PORTA, PIN5, PIN_HIGH); // on led
                      Delay_ms(500);

                      GPIO_u8setpinvalue(PORTA, PIN5, PIN_LOW); // off led
                      Delay_ms(500);

}
}

void USART3_IRQHandler(void)
{
    usart3_interrupt_flag = 1;            //flag
}
